image: registry.lighthouse-rbg.de/lighthouse/lighthouse-website

before_script:
  - npm install
  - npm install -g pm2

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pm2 start server.js --name "songbeamer"
    - pm2 status songbeamer
    - curl http://127.0.0.1/check
  when: always
